In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import datetime as dt
import math as time
import mysql.connector 
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
file1 = pd.read_csv("1.csv",parse_dates=['DateofRegistration'])
file2  = pd.read_csv("2.csv",parse_dates=['DateofRegistration'])
file3 = pd.read_csv("3.csv",parse_dates=['DateofRegistration'])
file4 = pd.read_csv("4.csv",parse_dates=['DateofRegistration'])
file5  = pd.read_csv("5.csv",parse_dates=['DateofRegistration'])
file6 = pd.read_csv("6.csv",parse_dates=['DateofRegistration'])
file7 = pd.read_csv("7.csv",parse_dates=['DateofRegistration'])
file8  = pd.read_csv("8.csv",parse_dates=['DateofRegistration'])
file9  = pd.read_csv("9.csv",parse_dates=['DateofRegistration'])
file10  = pd.read_csv("10.csv",parse_dates=['DateofRegistration'])
file11 = pd.read_csv("11.csv",parse_dates=['DateofRegistration'])
file12 = pd.read_csv("12.csv",parse_dates=['DateofRegistration'])
#file13  = pd.read_csv("13.csv",parse_dates=['DateofRegistration'])
#file14  = pd.read_csv("14.csv",parse_dates=['DateofRegistration'])

In [35]:
file8.head()

,OPDNumber,HTCNumber,patientid,Sex,MaritalStatus,EducationalLevel,Occupation,DateofRegistration,CounselingRecieved,tested_before,HTCApproach,HTCModel_Id,FinalResultType,Facilitycode,Districtcode,Provincedoce
0,1-5-41-2019-07-26-12-54-14.739,01-05-41-2019-V-00132,01-05-41-2019-A-00030,Female,Married,Secondary,SELF EMPLOYED,2019-07-10,Individual Pre-Test Information,No,CITC/ VCT,6,Positive,0A,5,1

In [11]:
Appointment_Data =pd.concat([file1,file2])
Appointment_Data =pd.concat([Appointment_Data,file3])
Appointment_Data =pd.concat([Appointment_Data,file4])
Appointment_Data =pd.concat([Appointment_Data,file5])
Appointment_Data =pd.concat([Appointment_Data,file6])
Appointment_Data =pd.concat([Appointment_Data,file7])
Appointment_Data =pd.concat([Appointment_Data,file8])
Appointment_Data =pd.concat([Appointment_Data,file9])
Appointment_Data =pd.concat([Appointment_Data,file10])
Appointment_Data =pd.concat([Appointment_Data,file11])
Appointment_Data =pd.concat([Appointment_Data,file12])
#Appointment_Data =pd.concat([Appointment_Data,file13])
#Appointment_Data =pd.concat([Appointment_Data,file14])

/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.
/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.


/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until
/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.
/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """
/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.


/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  import sys
/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.


/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':
/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  # Remove the CWD from sys.path while we load stuff.
/home/devoop/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  # This is added back by InteractiveShellApp.init_path()

In [12]:
Appointment_Data.shape

(5962, 16)

In [13]:
Appointment_Data.head()

,CounselingRecieved,DateofRegistration,Districtcode,EducationalLevel,Facilitycode,FinalResultType,HTCApproach,HTCModel_Id,HTCNumber,MaritalStatus,OPDNumber,Occupation,Provincedoce,Sex,patientid,tested_before
0,Yes,2019-04-18 00:00:00,5.0,NaN,29,Positive,NaN,0.0,01-05-29-2019-A-01060,M,1-5-29-2019-364,NaN,1.0,Male,01-05-29-2019-A-00025,NaN
1,Yes,2019-09-06 00:00:00,5.0,NaN,29,Positive,NaN,0.0,01-05-29-2019-A-01190,Married,1-5-29-2019-09-18-10-16-48.711,NaN,1.0,Male,01-05-29-2019-A-00061,Yes
2,Yes,2019-07-20 00:00:00,5.0,NaN,29,Positive,NaN,6.0,01-05-29-2019-E-01108,Divorced,1-5-29-2019-07-31-09-11-37.113,NaN,1.0,Male,01-05-29-2019-A-00051,No
3,Yes,2019-09-03 00:00:00,5.0,NaN,29,Positive,NaN,0.0,01-05-29-2019-V-00118,NaN,1-5-29-2019-09-18-09-50-09.136,NaN,1.0,Male,01-05-29-2019-A-00060,NaN
4,Yes,2019-02-12 00:00:00,5.0,NaN,29,Positive,NaN,6.0,01-05-29-2019-V-00251,NaN,1-5-29-2019-08-07-11-42-53.774,NaN,1.0,Male,NaN,No

In [14]:
Appointment_Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5962 entries, 0 to 2452
Data columns (total 16 columns):
CounselingRecieved    5936 non-null object
DateofRegistration    5956 non-null object
Districtcode          231 non-null float64
EducationalLevel      3873 non-null object
Facilitycode          231 non-null object
FinalResultType       5936 non-null object
HTCApproach           5820 non-null object
HTCModel_Id           5961 non-null float64
HTCNumber             5961 non-null object
MaritalStatus         5024 non-null object
OPDNumber             5961 non-null object
Occupation            549 non-null object
Provincedoce          231 non-null float64
Sex                   5916 non-null object
patientid             184 non-null object
tested_before         5789 non-null object
dtypes: float64(3), object(13)
memory usage: 791.8+ KB

In [15]:
Appointmet_List_data = Appointment_Data.to_csv (r'/media/devoop/GINA/Datasets/htc/wHTS.csv', index = None, header=True) #Don't forget to add '.csv' at the end of the path